runtime: python37

entrypoint:
  gunicorn -b :$PORT cros.factory.bundle_creator.app_engine.main:app

instance_class: B1
basic_scaling:
  max_instances: 1

handlers:
- url: /_ah/stubby/.*
  script: auto
